name: "Build and Deploy"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [node]

    steps:
      # Build

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      # Deploy

      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        with:
          user-email:
          create-target-branch-if-needed: true
          source-directory: "dist"
          destination-github-username: ${{ secrets.DEPLOY_GITHUB_USERNAME }}
          destination-repository-name: ${{ secrets.DEPLOY_GITHUB_REPOSITORY }}
